### ISSUE TITLE
Default text positioning incorrect when compared with AnPrez

### ISSUE THREAD

**Issue by akash14darshan** [AfterNow/ANPrezSDK#25]

**Comment by whoisvinod** [comment]
This issue seems to be happening for some Text assets in the SDK. Position seems to be wrong compared to that of ANPrez. Working on the issue.

T{02:00}

**Comment by whoisvinod** [comment]
Issue has been fixed and created PR for same at [#29](https://github.com/AfterNow/ANPrezSDK/pull/29). Review is pending.

T{05:00}
