### ISSUE TITLE
GLB still not unloaded properly. When clicking next/previous slide when a slide with glb is loading, the glb gets loaded from the previous slide and is never cleaned

### ISSUE THREAD

**Issue by akash14darshan** [AfterNow/ANPrezSDK#26]

**Comment by whoisvinod** [comment]
Tested with presentation id 07567780. This issue happens not so often but when user repeatedly clicks Previous and Next Slide buttons.

T{08:00}

**Comment by whoisvinod** [comment]
Found the cause of the issue. Working on the fix.

T{07:00}

**Comment by whoisvinod** [comment]
Issue has been fixed and created PR #30 for same

T{03:00}
